### ISSUE TITLE
Not Moving All Settings

### ISSUE THREAD

**Issue by DracoClaw** [Oocrop/bd-like-settings#1]
Not all settings pages are being moved. Clickable Edits, Spotify, and Emoji Utility, all show up on the side and dont have options to do the settings on the card.

**Comment by Oocrop** [comment]
These plugins have `pc-` prefix, which means they are built-in, if I remove the check for built-in plugins it may result in a big issue, such as `Plugins` section not displaying, thus, making it impossible to disable plugins or configure them

**Comment by DracoClaw** [comment]
Ah. That makes sense. Thanks so much.
