### ISSUE TITLE
Plugin breaks opening plugin settings from User Settings button context menu.

### ISSUE THREAD

**Issue by sepruko** [Oocrop/bd-like-settings#2]
Right click the cog, hover over Powercord and click on any of the plugin tabs, be greeted with a blank page.

![gif](https://i.imgur.com/yt4IFnJ.gif)

**Comment by Oocrop** [comment]
what plugin adds that option? I'll try to make my plugin compatible with it

**Comment by Oocrop** [comment]
@NotExactlyMeButMeh?

**Comment by sepruko** [comment]
@Oocrop Could have sworn that was a bundled feature, I guess not? In which case, I'm unaware as to what plugin this is.

**Comment by Oocrop** [comment]
it appeared a while ago for me, but I started to work on it only today because I'm lazy
going to close again once I release
